#!/bin/sh

# All Emojicode code should have prefix .emojic
infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.emojic
~/Emojicode/bin/emojicodec /tmp/code.emojic
chmod +x /tmp/code

cat - | /tmp/code

rm /tmp/code.emojic /tmp/code
